[package]
name = "btf-relocations-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
btf-relocations-common = { path = "../btf-relocations-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "btf-relocations"
path = "src/main.rs"
