[package]
name = "tc-bytes"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = { version = ">=0.11", features=["async_tokio"] }
aya-log = { git = "https://github.com/aya-rs/aya-log", branch = "main" }
tc-bytes-common = { path = "../tc-bytes-common", features=["user"] }
anyhow = "1.0.42"
clap = { version = "3.1", features = ["derive"] }
log = "0.4"
simplelog = "0.12"
tokio = { version = "1.18", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }

[[bin]]
name = "tc-bytes"
path = "src/main.rs"
